services:
  app:
    image: timeoff-app
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./config:/app/config
      - sqlite-data:/app/db
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - NODE_ENV=production
      - WAIT_HOSTS=redis:6379
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=30
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  sqlite-data:
  redis-data:
